### ISSUE TITLE
Rectangle rendering crash

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#617]
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
operator() at C:\mingw32\msys\1.0\home\michal\keeperrl/renderer.cpp:144
?? ??:0
?? ??:0
_ZN10WindowView11refreshViewEv at C:\mingw32\msys\1.0\home\michal\keeperrl/window_view.cpp:555
_ZNKSt13__atomic_baseIbE4loadESt12memory_order at c:/mingw32/i686-w64-mingw32/include/c++/bits/atomic_base.h:500
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0

**Comment by miki151** [comment]
#0  0x00000000 in ?? ()
#1  0x66998d6e in sf::RenderTarget::applyBlendMode(sf::BlendMode const&) () from C:\Program Files (x86)\Steam\steamapps\common\KeeperRL\sfml-graphics-2.dll
#2  0x66998f0d in sf::RenderTarget::resetGLStates() () from C:\Program Files (x86)\Steam\steamapps\common\KeeperRL\sfml-graphics-2.dll
#3  0x66999297 in sf::RenderTarget::draw(sf::Vertex const*, unsigned int, sf::PrimitiveType, sf::RenderStates const&) () from C:\Program Files (x86)\Steam\steamapps\common\KeeperRL\sfml-graphics-2.dll
#4  0x669a2a68 in sf::VertexArray::draw(sf::RenderTarget&, sf::RenderStates) const () from C:\Program Files (x86)\Steam\steamapps\common\KeeperRL\sfml-graphics-2.dll
#5  0x669989bd in sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&) () from C:\Program Files (x86)\Steam\steamapps\common\KeeperRL\sfml-graphics-2.dll
#6  0x6699f8a6 in sf::Shape::draw(sf::RenderTarget&, sf::RenderStates) const () from C:\Program Files (x86)\Steam\steamapps\common\KeeperRL\sfml-graphics-2.dll
#7  0x669989bd in sf::RenderTarget::draw(sf::Drawable const&, sf::RenderStates const&) () from C:\Program Files (x86)\Steam\steamapps\common\KeeperRL\sfml-graphics-2.dll
#8  0x00520e07 in operator() (__closure=<optimized out>) at renderer.cpp:144
#9  std::_Function_handler<void(), Renderer::drawFilledRectangle(const Rectangle&, sf::Color, boost::optional<sf::Color>)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at c:/mingw32/i686-w64-mingw32/include/c++/functional:2039
#10 0x00522606 in operator() (this=0x24b5af18) at c:/mingw32/i686-w64-mingw32/include/c++/functional:2439
#11 Renderer::drawAndClearBuffer (this=0xdf6fd28) at renderer.cpp:339
#12 0x0047bc57 in WindowView::refreshScreen (this=this@entry=0x11ed58e8, flipBuffer=flipBuffer@entry=true) at window_view.cpp:581
#13 0x0048386b in WindowView::refreshView (this=0x11ed58e8) at window_view.cpp:555
#14 0x00542e58 in renderLoop (view=0x11ed58e8, options=0xdf6fc18, finished=..., initialized=...) at main.cpp:61
#15 0x00542e95 in operator() (__closure=<optimized out>) at main.cpp:215
#16 _M_invoke<> (this=<optimized out>) at c:/mingw32/i686-w64-mingw32/include/c++/functional:1700
#17 operator() (this=<optimized out>) at c:/mingw32/i686-w64-mingw32/include/c++/functional:1688
#18 std::thread::_Impl<std::_Bind_simple<main(int, char**)::<lambda()>()> >::_M_run(void) (this=<optimized out>) at c:/mingw32/i686-w64-mingw32/include/c++/thread:115
#19 0x6fcb8c4f in libstdc++-6!execute_native_thread_routine () from C:\Program Files (x86)\Steam\steamapps\common\KeeperRL\libstdc++-6.dll
#20 0x64944f11 in pthread_create_wrapper () from C:\Program Files (x86)\Steam\steamapps\common\KeeperRL\libwinpthread-1.dll
#21 0x767d1287 in msvcrt!_itow_s () from C:\Windows\syswow64\msvcrt.dll
#22 0x767d1328 in msvcrt!_endthreadex () from C:\Windows\syswow64\msvcrt.dll
#23 0x764d338a in KERNEL32!BaseThreadInitThunk () from C:\Windows\syswow64\kernel32.dll
#24 0x771e9f72 in ntdll!RtlInitializeExceptionChain () from C:\Windows\SysWOW64\ntdll.dll
#25 0x771e9f45 in ntdll!RtlInitializeExceptionChain () from C:\Windows\SysWOW64\ntdll.dll
#26 0x00000000 in ?? ()
